version: '3.8'

services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped

    container_name: film_data_container
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: film_data_db
    ports:
      - "3307:3306"
    networks:
      - spring-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - film-data-volume:/var/lib/mysql


  spring-app:
    container_name: film-data-app
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/film_data_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - spring-network

#  gateway-app:
#    image: gateway-app
#
#    ports:
#      - "8080:8080"
#
#    networks:
#      - spring-network


networks:
  spring-network:
    driver: bridge

volumes:
  film-data-volume:
